export const metadata = {
    title: "Aussie Motors | Find New Cars",
    description: "Generated by create next app",
  };
  
  export default function RootLayout({ children }) {
    return <>{children}</>;
  }
  