const suburbs = [
    // Azad Kashmir
    { city: "Bhimbar", suburbs: ["Samahni", "Barnala", "Jandala", "Chowki", "Gulhan"] },
    { city: "Kotli", suburbs: ["Fatehpur Thakiala", "Sehnsa", "Khoiratta", "Nakyal", "Gulpur"] },
    { city: "Kotli District", suburbs: ["Khuiratta", "Sehnsa", "Tattapani", "Charhoi"] },
    { city: "Mirpur District", suburbs: ["Dadyal", "Chakswari", "Islamgarh", "Jarikas", "Kakra Town"] },
    { city: "Muzaffarābād", suburbs: ["Chattar", "Nalochi", "Chikar", "Rathoa", "Pir Chinasi"] },
    { city: "New Mirpur", suburbs: ["Sector F/4", "Sector D/4", "Sector C/3", "Allama Iqbal Road", "Khaliqabad"] },
    { city: "Rawala Kot", suburbs: ["Paniola", "Choti Gala", "Sanghar", "Chare", "Toli Peer"] },
  
    // Balochistan
    { city: "Alik Ghund", suburbs: ["Mulla", "Greshik", "Dasht", "Taghaz", "Shoran"] },
    { city: "Awārān District", suburbs: ["Awārān Town", "Mashkai", "Jhal Jhao", "Buzdar", "Kohlu"] },
    { city: "Barkhan", suburbs: ["Barkhan City", "Bagh", "Ladkhan", "Rakhni", "Nal"] },
    { city: "Bela", suburbs: ["Old Bela", "Winder", "Gadani", "Liari", "Uthal"] },
    { city: "Bhag", suburbs: ["Sanni", "Bhag City", "Dhadar", "Harank", "Mach"] },
    { city: "Bārkhān District", suburbs: ["Barkhan", "Bagh", "Ladkhan"] },
    { city: "Chaman", suburbs: ["Roghani", "Toba Achakzai", "Gulistan", "Shahbaz Town", "Qila Abdullah"] },
    { city: "Chowki Jamali", suburbs: ["Chowki Jamali Center", "Naseerabad", "Kashmore"] },
    { city: "Chāgai District", suburbs: ["Dalbandin", "Nok Kundi", "Taftan", "Saindak"] },
    { city: "Dadhar", suburbs: ["Dhadar Town", "Sanni", "Dhadar Industrial Area"] },
    { city: "Dalbandin", suburbs: ["Railway Colony", "Chaghi", "Tahlab"] },
    { city: "Dera Bugti", suburbs: ["Sui", "Pirkoh", "Loti", "Zin", "Dera Bugti Town"] },
    { city: "Dera Bugti District", suburbs: ["Dera Bugti", "Sui", "Loti"] },
    { city: "Duki", suburbs: ["Duki Town", "Paspin", "Kot Kili"] },
    { city: "Gadani", suburbs: ["Shipbreaking Yard", "Gadani Beach", "Dhabeji"] },
    { city: "Garhi Khairo", suburbs: ["Garhi City", "Koto Moro", "Kot Jan"] },
    { city: "Gwadar", suburbs: ["New Town", "Jinnah Avenue", "Sangar Housing", "Marine Drive"] },
    { city: "Harnai", suburbs: ["Harnai Town", "Shahrag", "Wadh"] },
    { city: "Jhal Magsi District", suburbs: ["Gandawah", "Magsi Town", "Jhal Magsi"] },
    { city: "Jiwani", suburbs: ["Jiwani Port", "Jiwani Bazaar", "Mallah Colony"] },
    { city: "Jāfarābād District", suburbs: ["Dera Allah Yar", "Usta Muhammad", "Gandar"] },
    { city: "Kalat", suburbs: ["Surab", "Manguchar", "Kalat Town"] },
    { city: "Kalāt District", suburbs: ["Kalat", "Kharan", "Nagha Kalat"] },
    { city: "Khadan Khak", suburbs: ["Khadan", "Suraap", "Gidar"] },
    { city: "Kharan", suburbs: ["Kharan Town", "Nushki", "Zahidan Road"] },
    { city: "Khuzdar", suburbs: [
      "Khuzdar City", 
      "Jinnah Town", 
      "Civil Colony", 
      "Khalidabad", 
      "Main Bazaar", 
      "Airport Road", 
      "Koshak", 
      "Mir Gul Hassan Colony", 
      "Gareebabad", 
      "Azizabad", 
      "Nasarabad", 
      "Sheikh Umar Colony", 
      "Faizabad", 
      "Allahabad", 
      "Chakar Khan Road", 
      "Magsi Colony", 
      "Wadh", 
      "Ornach", 
      "Sarawan Colony", 
      "Bagbana", 
      "Mustang Chowk", 
      "Kalat Road", 
      "B&R Colony", 
      "Satellite Town", 
      "Saddar", 
      "Mulla Khan Colony", 
      "Kalat Khairabad", 
      "Naal"
    ]},
    { city: "Khuzdār District", suburbs: ["Khuzdar", "Wadh", "Ornach"] },
    { city: "Khārān District", suburbs: ["Kharan", "Nagha", "Sarak Road"] },
    { city: "Kohlu", suburbs: ["Kahan", "Machh", "Nal"] },
    { city: "Kot Malik Barkhurdar", suburbs: ["Kot City", "Malik Mohallah", "Qasba"] },
    { city: "Lasbela District", suburbs: ["Uthal", "Bela", "Gadani", "Dureji"] },
    { city: "Loralai", suburbs: ["Loralai Town", "Dargai", "Kili Ismail"] },
    { city: "Loralai District", suburbs: ["Loralai", "Killa Saifullah", "Duki"] },
    { city: "Mach", suburbs: ["Machh Town", "Tambo", "Machh Cantonment"] },
    { city: "Mastung", suburbs: ["Mastung City", "Dasht", "Kalat Road"] },
    { city: "Mastung District", suburbs: ["Mastung", "Dasht", "Kanak"] },
    { city: "Mehrabpur", suburbs: ["Main Bazaar", "Mehrabpur Town", "Old Mehrabpur"] },
    { city: "Mūsa Khel District", suburbs: ["Musa Khel", "Kot Kili", "Kohlu"] },
    { city: "Nasīrābād District", suburbs: ["Dera Murad Jamali", "Chattar", "Tambo"] },
    { city: "Nushki", suburbs: ["Nushki Town", "Chaghi Road", "Tahlab"] },
    { city: "Ormara", suburbs: ["Naval Colony", "Ormara Beach", "Jinnah Naval Base"] },
    { city: "Panjgūr District", suburbs: ["Paroom", "Gichk", "Khudabadan"] },
    { city: "Pasni", suburbs: ["Pasni Fish Harbour", "Jiwani Road", "Marine Colony"] },
    { city: "Pishin", suburbs: ["Saranan", "Pishin Town", "Killi Mengal"] },
    { city: "Qila Saifullāh District", suburbs: ["Qila Saifullah", "Zhob Road", "Muslim Bagh"] },
    { city: "Quetta", suburbs: ["Sariab Road", "Hanna Urak", "Satelite Town", "Zarghoon Town", "Hazara Town"] },
    { city: "Quetta District", suburbs: ["Quetta City", "Pashtunabad", "Hazara Town"] },
    { city: "Sibi", suburbs: ["Talli Road", "Sibi Town", "Nari Gorge"] },
    { city: "Sohbatpur", suburbs: ["Sohbatpur Town", "Dera Allah Yar"] },
    { city: "Surab", suburbs: ["Surab Town", "Gidar", "Nalag"] },
    { city: "Turbat", suburbs: ["Main Bazaar", "Kech Colony", "Tump", "Shahrak"] },
    { city: "Usta Muhammad", suburbs: ["City Center", "Bhag", "Chattar"] },
    { city: "Uthal", suburbs: ["Uthal City", "Winder", "Gadani"] },
    { city: "Zhob", suburbs: ["Zhob City", "Murgha Faqirzai", "Killi Khidmatgar"] },
    { city: "Zhob District", suburbs: ["Zhob", "Murgha", "Qila Saifullah"] },
    { city: "Ziarat", suburbs: ["Ziarat Town", "Kawas", "Warcha"] },
    { city: "Ziārat District", suburbs: ["Ziarat", "Kawas", "Warcha"] },
  
    // Federally Administered Tribal Areas
    { city: "Alizai", suburbs: ["Upper Alizai", "Lower Alizai", "Sharak", "Gulab Khan", "Saray"] },
    { city: "Gulishah Kach", suburbs: ["Kach Town", "Gulishah Center", "Zor Kach", "Dariyan"] },
    { city: "Landi Kotal", suburbs: ["Jamrud", "Shagai Fort", "Landi Khana", "Torkham", "Mian Morcha"] },
    { city: "Miran Shah", suburbs: ["Datta Khel", "Spinwam", "Ghulam Khan", "Khaisura"] },
    { city: "North Wazīristān Agency", suburbs: ["Mir Ali", "Miran Shah", "Razmak", "Shewa", "Eidak"] },
    { city: "Shinpokh", suburbs: ["Shinpokh Center", "Dargai", "Girdi Jungle", "Wach Darra"] },
    { city: "South Wazīristān Agency", suburbs: ["Wana", "Shakai", "Angoor Adda", "Kaniguram", "Makin"] },
    { city: "Wana", suburbs: ["Azam Warsak", "Shakai Valley", "Birmal", "Spin", "Raghzai"] },
  
    // Gilgit-Baltistan
    { city: "Barishal", suburbs: ["Gulmit", "Gojal", "Passu", "Hussaini", "Shimshal"] },
    { city: "Gilgit", suburbs: ["Jutial", "Majini Muhalla", "Khomer", "Amphary", "Sultanabad"] },
    { city: "Skardu", suburbs: ["Saddar", "Gamba Skardu", "Shigar", "Katpana", "Hussainabad"] },
  
    // Khyber Pakhtunkhwa
    { city: "Abbottabad", suburbs: ["Mandian", "Nawanshehr", "Jhangi", "Supply Bazaar", "Thandiani"] },
    { city: "Akora", suburbs: ["Akora Khattak", "Jehangira", "Tarbela Road"] },
    { city: "Aman Garh", suburbs: ["Main Bazaar", "Khan Colony", "Gulzar Colony"] },
    { city: "Amirabad", suburbs: ["Amirabad Center", "Kacha Road", "New Amirabad"] },
    { city: "Ashanagro Koto", suburbs: ["Koto Town", "Upper Koto", "Lower Koto"] },
    { city: "Baffa", suburbs: ["Baffa Town", "Chitti Gatti", "Batang Bala"] },
    { city: "Bannu", suburbs: ["Bannu City", "Mandew", "Nurar", "Domel", "Bazar Ahmed Khan"] },
    { city: "Bat Khela", suburbs: ["Batkhela Bazaar", "Thana", "Sakhakot", "Jalala"] },
    { city: "Battagram", suburbs: ["Battagram Town", "Alai", "Thakot", "Landay Sar"] },
    { city: "Battagram District", suburbs: ["Battagram", "Ajmera", "Allai Valley"] },
    { city: "Buner District", suburbs: ["Daggar", "Pir Baba", "Sultanwas", "Gadezai"] },
    { city: "Charsadda", suburbs: [
      "Charsadda City", 
      "Umerzai", 
      "Prang", 
      "Rajjar", 
      "Shabqadar", 
      "Tangi", 
      "Dheri Zardad", 
      "Utmanzai", 
      "Sherpao", 
      "Tarnab", 
      "Hastnagar", 
      "Dargai", 
      "Saro Kallay", 
      "Turangzai", 
      "Katozai", 
      "Shiekhabad", 
      "Khanmai", 
      "Gulabad", 
      "Harichand", 
      "Behlola", 
      "Mandani", 
      "Mian Isa", 
      "Kheshgi Bala", 
      "Kheshgi Payan", 
      "Matta Mughalkhel", 
      "Shodag", 
      "Ibrahimzai", 
      "Mohib Banda", 
      "Zarif Korona", 
      "Kharki", 
      "Mardari", 
      "Bibi Khel", 
      "Akbar Abad"
    ]},
    { city: "Cherat Cantonement", suburbs: ["Cherat Town", "Cherat Fort", "Shah Mansoor"] },
    { city: "Chitral", suburbs: ["Drosh", "Booni", "Ayun", "Garum Chashma", "Shandur"] },
    { city: "Dera Ismail Khan", suburbs: [
      "Topanwala", 
      "Commissioner Colony", 
      "Cantt Area", 
      "Haidri", 
      "Muryali", 
      "Tank Adda", 
      "Gomal University", 
      "College Town", 
      "Bannu Road", 
      "Pahar Pur", 
      "Kacha Pakka", 
      "Din Pur", 
      "Kotli Imam", 
      "Maddi Town", 
      "Pir Zaki Shah", 
      "Malikhel", 
      "Ratta Kulachi Town", 
      "Mandi Town", 
      "Islamabad Mohalla", 
      "New Darya Khan", 
      "Kotla Saidan", 
      "Daraban Kalan", 
      "Hafizabad", 
      "Sheikh Yousaf", 
      "Kiri Khaisur", 
      "Mahallah Qasaban", 
      "Liaqat Park", 
      "Chowgalla", 
      "Ramak", 
      "Gulshan-e-Amin", 
      "Kulachi", 
      "Muryali Town", 
      "Shorkot", 
      "Malgani Town", 
      "Mochiwal", 
      "Grid Station Colony"
    ]},
    { city: "Dera Ismāīl Khān District", suburbs: ["Dera Town", "Paharpur", "Kulachi"] },
    { city: "Doaba", suburbs: ["Doaba Center", "Main Bazaar", "Doaba Bypass"] },
    { city: "Hangu", suburbs: ["Hangu Town", "Thall", "Darsamand", "Shahu Khel"] },
    { city: "Haripur", suburbs: ["Khalabat Township", "Sarai Saleh", "Khanpur", "Darwesh"] },
    { city: "Havelian", suburbs: ["Main Bazaar", "Darband Road", "Langra", "Nara"] },
    { city: "Kakad Wari Dir Upper", suburbs: ["Dir Town", "Sheringal", "Barawal"] },
    { city: "Karak", suburbs: ["Karak Town", "Takht-e-Nasrati", "Latamber", "Sabirabad"] },
    { city: "Khalabat", suburbs: ["Khalabat Township", "Mohallah Naeemabad", "Sector No 4"] },
    { city: "Kohat", suburbs: ["KDA Kohat", "Togh Bala", "Gumbat", "Jangal Khel"] },
    { city: "Kulachi", suburbs: ["Kulachi Town", "Paharpur", "Qureshi Town"] },
    { city: "Lachi", suburbs: ["Lachi Town", "Dando Road", "Bazaar Road"] },
    { city: "Lakki", suburbs: ["Lakki Marwat", "Titterkhel", "Darra Tang"] },
    { city: "Mansehra", suburbs: ["Ghazi Kot", "Sheikh Abad", "Shinkiari", "Channia"] },
    { city: "Mardan", suburbs: ["Sheikh Maltoon Town", "Baghdada", "Cantt", "Par Hoti", "Toru"] },
    { city: "Mingora", suburbs: ["Saidu Sharif", "Malookabad", "Takhtaband", "Kanju Township"] },
    { city: "Noorabad", suburbs: ["Main Market", "Khanqah Road", "Noorabad Center"] },
    { city: "Nowshera", suburbs: [
      "Nowshera Cantt", 
      "Nowshera Kalan", 
      "Pabbi", 
      "Akora Khattak", 
      "Risalpur", 
      "Ziarat Kaka Sahib", 
      "Amangarh", 
      "Manki Sharif", 
      "Azakhel", 
      "Jehangira", 
      "Pir Sabaq", 
      "Kheshgi Bala", 
      "Kheshgi Payan", 
      "Kabul River", 
      "Dag Ismail Khel", 
      "Adamzai", 
      "Spin Khak", 
      "Misri Banda", 
      "Taru Jabba", 
      "Jalozai", 
      "Mughalabad", 
      "Shireen Kotha", 
      "Nizampur", 
      "Chapri", 
      "Qaziabad", 
      "Dheri Kati Khel", 
      "Hakimabad", 
      "Khawri", 
      "Mera Jalozai", 
      "Saleh Khana"
    ]},
    { city: "Nowshera Cantonment", suburbs: ["Cantt Area", "Sadar Bazar", "Amangarh"] },
    { city: "Pabbi", suburbs: ["Main Pabbi", "Mughal Key", "Pir Sabaq"] },
    { city: "Paharpur", suburbs: ["Dera Adda", "Paharpur Bazar", "Ghazi Road"] },
    { city: "Peshawar", suburbs: ["Hayatabad", "University Town", "Saddar", "Kohat Road", "Gulbahar"] },
    { city: "Risalpur Cantonment", suburbs: ["Cantt Area", "Risalpur Bazaar", "Academy Town"] },
    { city: "Sarai Naurang", suburbs: ["Naurang City", "Mohallah Kakki", "Main Bazaar"] },
    { city: "Shabqadar", suburbs: ["Shabqadar Bazaar", "Shankaro", "Gulabad"] },
    { city: "Shingli Bala", suburbs: ["Bala Center", "Bazaar Shingli", "Lower Shingli"] },
    { city: "Shorkot", suburbs: ["Shorkot Bazaar", "Cantt Area", "Township"] },
    { city: "Swabi", suburbs: [
      "Main Swabi City", 
      "Topi", 
      "Shewa Adda", 
      "Gadoon Amazai", 
      "Maneri Payan", 
      "Maneri Bala", 
      "Marghuz", 
      "Zaida", 
      "Chota Lahor", 
      "Yar Hussain", 
      "Kotha", 
      "Ismaila", 
      "Tordher", 
      "Shahmansoor", 
      "Kalabat", 
      "Jhanda", 
      "Gabasni", 
      "Bamkhel", 
      "Beka", 
      "Kund Park", 
      "Jehangira", 
      "Panjpir", 
      "Kalu Khan", 
      "Salim Khan", 
      "Charsadda Road", 
      "Bam Khel", 
      "Tarbela Dam Colony", 
      "Kala", 
      "Darra", 
      "Razzar", 
      "Manki", 
      "Gohati", 
      "Naranji", 
      "Beka Sher Garh", 
      "Mangal Chai"
    ]},
    { city: "Tangi", suburbs: ["Tangi Bazaar", "Pir Baba Road", "Qazi Abad"] },
    { city: "Tank", suburbs: ["Tank Town", "Gomal", "Kot Hakim Khan"] },
    { city: "Thal", suburbs: ["Thal City", "Thal Bazar", "Kurram Road"] },
    { city: "Topi", suburbs: ["Topi Town", "Gadoon Industrial Area", "Tarbela Road"] },
    { city: "Upper Dir", suburbs: ["Dir Town", "Sheringal", "Wari"] },
    { city: "Utmanzai", suburbs: ["Utmanzai Town", "Rashakai", "Mohallah Rehmatabad"] },
    { city: "Zaida", suburbs: ["Zaida Town", "Zaida Bazaar", "Main Road"] },
  
      // Punjab
      { city: "Ahmadpur Sial", suburbs: ["Chak No. 186", "Shahpur", "Pindi Sultani"] },
      { city: "Ahmedpur East", suburbs: ["Ahmedpur Bazar", "Dera Nawab Sahib", "Kotla Musa Khan"] },
      { city: "Alipur Chatha", suburbs: ["Alipur Center", "Kot Ishaq", "Chak Bhatti"] },
      { city: "Arifwala", suburbs: ["Chak No. 58 EB", "Chak No. 69 EB", "Arifwala City"] },
      { city: "Attock Tehsil", suburbs: ["Attock City", "Fateh Jang", "Hasan Abdal", "Hazro"] },
      { city: "Baddomalhi", suburbs: ["Baddomalhi Town", "Noorpur", "Qila Baddomalhi"] },
      { city: "Bahawalnagar", suburbs: ["Minchinabad", "Fort Abbas", "Dharanwala", "Dunga Bunga"] },
      { city: "Bahawalpur", suburbs: [
        "Model Town A", 
        "Model Town B", 
        "Satellite Town", 
        "Muslim Town", 
        "Cantt Area", 
        "Shadab Colony", 
        "Chah Fateh Khan", 
        "Hasilpur Road", 
        "Gulzar-e-Sadiq", 
        "Civil Lines", 
        "One Unit Staff Colony", 
        "Farid Gate", 
        "Trust Colony", 
        "Fareed Town", 
        "Nishtar Town", 
        "Muhammadia Colony", 
        "Rafi Qamar Road", 
        "Qasim Town", 
        "Hashmi Garden", 
        "Basti Hamaitian", 
        "Khanqah Sharif", 
        "Islamia Colony", 
        "Green Town", 
        "Saddar Bazaar", 
        "Yazman Road", 
        "Railway Road", 
        "University Town", 
        "Ahmedpuri Gate", 
        "Gulshan-e-Farid", 
        "Khairpur Tamewali Road", 
        "Old City Bahawalpur", 
        "Gulzar Colony", 
        "Khan Village", 
        "Bahawalpur City", 
        "Royal City Housing Scheme", 
        "Riaz Colony", 
        "Qayyum Town", 
        "Shams Colony", 
        "Benazir Colony", 
        "Shahdara", 
        "Madinat-ul-Hikmah", 
        "Darbar Mahal", 
        "Baghdad-ul-Jadeed Campus", 
        "Bahawalpur Housing Scheme", 
        "Hakeem Bazar", 
        "Azam Town", 
        "Jinnah Town", 
        "Airport Road", 
        "Khairpur Road", 
        "Basti Malkan", 
        "Basti Sheikh Wahan", 
        "Shahdra Town", 
        "Jhangi Wala Road", 
        "Model Town C", 
        "Basti Abbas Nagar", 
        "Baghdad Colony", 
        "Dubai Mahal Colony", 
        "Rafi Garden", 
        "Garden Town", 
        "Ahmedpur East Road", 
        "Sadiq Colony", 
        "Basti Hakra"
      ]},
      { city: "Bakhri Ahmad Khan", suburbs: ["Bakhri Village", "Chak No. 127", "Main Bazar"] },
      { city: "Basirpur", suburbs: ["Chak No. 46/GD", "Basirpur City", "Mustafabad"] },
      { city: "Basti Dosa", suburbs: ["Dosa City", "Chak No. 20", "Basti Mirpur"] },
      { city: "Begowala", suburbs: ["Begowala Town", "Begowala Chak", "Haji Pura"] },
      { city: "Bhakkar", suburbs: ["Darya Khan", "Kallur Kot", "Mankera", "Behal"] },
      { city: "Bhalwal", suburbs: ["Bhalwal City", "Phularwan", "Nathuwala"] },
      { city: "Bhawana", suburbs: ["Chak 63 JB", "Chak 65 JB", "Bhawana Town"] },
      { city: "Bhera", suburbs: ["Bhera City", "Bhera Bypass", "Kot Bhera"] },
      { city: "Bhopalwala", suburbs: ["Main Bazar", "Bhopalwala Center"] },
      { city: "Burewala", suburbs: ["Chak 461/EB", "Lodhran Road", "College Town"] },
      { city: "Chak Azam Saffo", suburbs: ["Azam Town", "Gulzar Chowk", "Chak No. 120"] },
      { city: "Chak Jhumra", suburbs: ["Gatwala", "Samundri Road", "Chak No. 214"] },
      { city: "Chak One Hundred Twenty Nine Left", suburbs: ["Basti 129", "Center 129", "Chak Market"] },
      { city: "Chak Thirty-one -Eleven Left", suburbs: ["Chak Bazaar", "Thathoo Road"] },
      { city: "Chak Two Hundred Forty-Nine TDA", suburbs: ["TDA 249 Town", "Main Chowk"] },
      { city: "Chakwal", suburbs: [
        "Talagang Road", 
        "Balkassar", 
        "Civil Lines", 
        "Railway Road", 
        "Chakwal Cantt", 
        "Dheedwal", 
        "Jhelum Road", 
        "Neela Wahn", 
        "Kallar Kahar", 
        "Buchal Kalan", 
        "Bhaun", 
        "Dhudial", 
        "Kahoot", 
        "Mulhal Mughlan", 
        "Khairpur", 
        "Miani", 
        "Mohalla Islamia", 
        "Fatehpur", 
        "Sargojra", 
        "Choa Saidan Shah", 
        "Alamabad Colony", 
        "Shah Muhammad Wali", 
        "Chak Umra", 
        "Mangwal", 
        "Bhoun Chowk", 
        "Wara Chakwal", 
        "Dhoke Amb", 
        "Kasswal", 
        "Tamman", 
        "Tatral", 
        "Karsal", 
        "Sikandarabad", 
        "Pir Phulahi", 
        "Dalwal", 
        "Latifal", 
        "Alamabad", 
        "Ratta Mohra", 
        "Pinwal", 
        "Lawa", 
        "Talagang City", 
        "Dhurnal", 
        "Dhok Feroze", 
        "Kot Qazi", 
        "Kot Sarang"
      ]},
      { city: "Chawinda", suburbs: ["Chawinda City", "Chak Amru", "Jandiala"] },
      { city: "Chichawatni", suburbs: ["Sahiwal Road", "Ghaziabad", "Abdullah Town"] },
      { city: "Chiniot", suburbs: ["Chenab Nagar", "Lalian", "Bhowana", "Laliyan"] },
      { city: "Chishtian", suburbs: [
        "Main Bazaar", 
        "Farooqabad", 
        "Gulshan-e-Madina", 
        "Model Town", 
        "Satellite Town", 
        "Green Town", 
        "Civil Lines", 
        "Fateh Town", 
        "Azizabad", 
        "Abbas Nagar", 
        "Khan Colony", 
        "Mohalla Islamabad", 
        "Iqbal Nagar", 
        "College Town", 
        "Anwarabad", 
        "Nishat Colony", 
        "Ghafoorabad", 
        "Rehman Colony", 
        "Saddar Bazar", 
        "Hameedpura", 
        "Basti Mian Allah Yar", 
        "Mumtazabad", 
        "Chishtian Cantt", 
        "Sharifabad", 
        "Mohalla Sheikhanwala", 
        "Amin Town", 
        "Gulshan-e-Iqbal", 
        "Muslim Town", 
        "Baghbanpura", 
        "Basti Shah Nazar", 
        "Chak No. 13/G"
      ]},
      { city: "Choa Saidanshah", suburbs: ["Khewra", "Dandot RS", "Kallar Kahar"] },
      { city: "Chuhar Kana", suburbs: ["Kot Bhaga", "Khudian", "Harchoki"] },
      { city: "Chunian", suburbs: ["Allahabad", "Halla Road", "Phool Nagar"] },
      { city: "Daira Din Panah", suburbs: ["Dera Ghazi Khan Road", "Shahpur Road"] },
      { city: "Dajal", suburbs: ["Dajal Town", "Jampur Road"] },
      { city: "Dandot RS", suburbs: ["Dandot Mines", "Main Dandot"] },
      { city: "Darya Khan", suburbs: ["Mianwali Road", "Chak No. 9", "Chowk Azam"] },
      { city: "Daska", suburbs: [
        "Main Bazaar", 
        "Saddar Bazar", 
        "College Road", 
        "Circular Road", 
        "Civil Lines", 
        "Imam Sahib", 
        "Katchery Road", 
        "Model Town", 
        "Sambrial Road", 
        "Fatehgarh", 
        "Sheikhupura Road", 
        "Ghazi Road", 
        "Mianapura", 
        "Muhammadpura", 
        "Awan Town", 
        "Gulshan Colony", 
        "Akbarabad", 
        "Farid Town", 
        "Hajipura", 
        "Sialkot Road", 
        "Tandalianwala", 
        "Hajipura No. 2", 
        "Habibpura", 
        "Ranjhai", 
        "Bangla Road", 
        "Daska Kalan", 
        "Kot Daska", 
        "Islamabad Colony", 
        "Dhillon Town", 
        "Nawaz Town", 
        "Sabzi Mandi Area"
      ]},
      { city: "Daud Khel", suburbs: ["Mianwali Road", "Daud Khel Bypass"] },
      { city: "Daultala", suburbs: ["Daultala Town", "Chakwal Road"] },
      { city: "Dera Ghazi Khan", suburbs: ["Model Town", "Shah Sadar Din", "Kot Chatta"] },
      { city: "Dhanot", suburbs: ["Dhanot Center", "Basti Malook", "Shujabad Road"] },
      { city: "Dhaunkal", suburbs: ["Dhaunkal Center", "Gujranwala Road"] },
      { city: "Dhok Awan", suburbs: ["Village Awan", "Ratta Road"] },
      { city: "Dijkot", suburbs: ["Faisalabad Road", "Chak No. 273 RB"] },
      { city: "Dinan Bashnoian Wala", suburbs: ["Dinan Center", "Kot Sultan"] },
      { city: "Dinga", suburbs: ["Chak No. 43", "Main Dinga Bazar"] },
      { city: "Dipalpur", suburbs: ["Okara Road", "Chak 40/D", "Gulshan Town"] },
      { city: "Dullewala", suburbs: ["Dullewala City", "Chak No. 77"] },
      { city: "Dunga Bunga", suburbs: ["Fort Abbas Road", "Main Bazar"] },
      { city: "Dunyapur", suburbs: ["Lodhran Road", "Jinnah Chowk"] },
      { city: "Eminabad", suburbs: ["Ravi Road", "Main Bazar"] },
      {
        city: "Faisalabad",
        suburbs: [
          "Jinnah Colony", 
          "Peoples Colony", 
          "Madina Town", 
          "D-Type Colony", 
          "Samanabad", 
          "Gulistan Colony", 
          "Ghulam Muhammad Abad", 
          "Millat Town", 
          "Susan Road", 
          "Allama Iqbal Colony", 
          "Batala Colony", 
          "Eden Valley", 
          "Eden Gardens", 
          "Samundari Road", 
          "Kohinoor City", 
          "Tariqabad", 
          "Razaabad", 
          "Nazimabad", 
          "Factory Area", 
          "Satiana Road", 
          "Khanuana", 
          "Faisal Garden", 
          "Model City", 
          "Abdullahpur", 
          "Usman Town", 
          "Iqbal Town", 
          "Gulshan Colony", 
          "Chak Jhumra", 
          "Bawa Chak", 
          "Muhammadpura", 
          "Shadab Colony", 
          "Ismail City", 
          "Saifabad", 
          "Waris Pura", 
          "Chak 208", 
          "Green View Colony", 
          "Faisal City", 
          "Mansoorabad", 
          "Jaranwala Road", 
          "Shalimar Park", 
          "Officer Colony", 
          "University Town", 
          "Paradise Valley", 
          "Canal Road", 
          "Haripur", 
          "Nisar Colony", 
          "Makkah Town", 
          "Nighabanpura", 
          "Mian Town", 
          "Model Town", 
          "Muhammad Nagar", 
          "Jhanda Singh Wala", 
          "Ali Town", 
          "Sir Syed Town", 
          "Sitara Colony", 
          "Awami Colony", 
          "Gatwala", 
          "Lyallpur Town", 
          "Punjab Govt Servant Housing Colony", 
          "Millat Estate", 
          "Siddiquia Mill Colony", 
          "Chak 7 JB", 
          "Niamuana", 
          "Nawabanwala", 
          "Yasrab Colony", 
          "Lasani Town", 
          "Khayaban Garden", 
          "Sheikh Colony", 
          "Doctor City", 
          "Rehman Gardens", 
          "Al Noor Garden", 
          "Al Hamra Town", 
          "Royal City", 
          "Ajwa City", 
          "Model City 2", 
          "Rabbani Colony", 
          "Garden City", 
          "Wapda City", 
          "FDA City", 
          "Maqbool Road", 
          "Sahianwala", 
          "Ghulam Muhammad Town", 
          "Islampura", 
          "Chak 209 RB", 
          "Chak 239 RB", 
          "Jhumra Road", 
          "Pahari Ground", 
          "Malikpur"
        ]
      }
      ,
      { city: "Faqirwali", suburbs: ["Faqirwali Center", "Hujra Road"] },
      { city: "Faruka", suburbs: ["Faruka Town", "Lalian Road"] },
      { city: "Fazilpur", suburbs: ["Fazilpur City", "Dera Ghazi Khan Road"] },
      { city: "Ferozewala", suburbs: ["Ferozewala Town", "Shahdara", "Kala Khatai"] },
      { city: "Fort Abbas", suburbs: ["Chak No. 209/EB", "Toba Road"] },
      { city: "Garh Maharaja", suburbs: ["Garh Town", "Jhang Road"] },
      { city: "Gojra", suburbs: ["Gojra City", "Painsara", "Gadda Khana"] },
      { city: "Gujar Khan", suburbs: ["Bali Shah", "Daultala", "Jatli"] },
      { city: "Gujranwala", suburbs: [
        "Satellite Town", 
        "Model Town", 
        "Peoples Colony", 
        "Garden Town", 
        "Civil Lines", 
        "Wapda Town", 
        "Gulshan Colony", 
        "Citi Housing", 
        "DC Colony", 
        "Cannon Valley", 
        "Professors Colony", 
        "Ferozwala", 
        "Gujranwala Cantt", 
        "Shalimar Town", 
        "Shaheenabad", 
        "Khokhar Town", 
        "Aroop Town", 
        "Alipur Chatha", 
        "Nandi Pur Town", 
        "Gill Road", 
        "Fateh Garh", 
        "Nowshera Road", 
        "Khiali Shah Pur", 
        "Nandipur", 
        "Rahwali", 
        "Sialkoti Gate", 
        "Jinnah Road", 
        "Trust Colony", 
        "Jinnah Colony", 
        "Rana Colony", 
        "Gohadpur", 
        "Talwandi Musa Khan", 
        "Farid Town", 
        "Qila Didar Singh", 
        "Gujjar Town", 
        "Bismillah Colony", 
        "Iqbal Town", 
        "Baghbanpura", 
        "Green Town", 
        "Gurunanakpura", 
        "Hafizabad Road", 
        "Sheikhupura Road", 
        "Royal Palm City", 
        "Al Hafiz Town", 
        "Ali Pur Chatha", 
        "Khiali", 
        "Eminabad", 
        "Pasrur Road", 
        "Waris Pura", 
        "Railway Road", 
        "Chaman Shah", 
        "Kot Ishaq", 
        "Kamoke", 
        "Dhulleke", 
        "Nanakpura", 
        "Khokhar Key", 
        "Gujjar Pura", 
        "Waris Colony", 
        "Yaseenabad", 
        "Mian Sansi Town", 
        "Saddar Town", 
        "Shadman Town", 
        "Industrial Estate", 
        "Saddar Cantt", 
        "Green Valley", 
        "Qila Mian Singh", 
        "Satellite Town Extension", 
        "Al Madina Town", 
        "Banker Colony", 
        "Murad Colony", 
        "Rachna Town", 
        "Shadbagh", 
        "Chand Da Qila"
      ]},
      { city: "Gujranwala Division", suburbs: ["Gujrat", "Sialkot", "Narowal"] },
      { city: "Gujrat", suburbs: ["Shadman Colony", "Model Town", "Railway Road"] },
      { city: "Hadali", suburbs: ["Hadali Center", "Mangowal"] },
      { city: "Hafizabad", suburbs: ["Pindi Bhattian", "Kot Sarwar", "Sukheke Mandi"] },
      { city: "Harnoli", suburbs: ["Harnoli Town", "Chak No. 169"] },
      { city: "Harunabad", suburbs: ["Model Town", "Basti Islamabad"] },
      { city: "Hasan Abdal", suburbs: ["Cantt Area", "GT Road", "Shahbaz Garhi"] },
      { city: "Hasilpur", suburbs: ["Model Town", "Basti Kalaywala"] },
      { city: "Haveli Lakha", suburbs: ["Chak No. 25/SP", "Haveli Center"] },
      { city: "Hazro", suburbs: ["Hazro Town", "Attock Road"] },
      { city: "Hujra Shah Muqeem", suburbs: ["Chak No. 28/SP", "Gulzar Chowk"] },
      { city: "Jahanian Shah", suburbs: ["Jahanian City", "Chak No. 134"] },
      { city: "Jalalpur Jattan", suburbs: ["New Jalalpur", "Old Jalalpur"] },
      { city: "Jalalpur Pirwala", suburbs: ["Pirwala Road", "Sultanpur"] },
      { city: "Jampur", suburbs: ["Kot Addu Road", "Jampur Center"] },
      { city: "Jand", suburbs: ["Jand Town", "Dhok Pathan"] },
      { city: "Jandiala Sher Khan", suburbs: ["Jandiala Bazaar", "Gulzar Chowk"] },
      { city: "Jaranwala", suburbs: [
        "Main Bazaar", 
        "Civil Lines", 
        "Jinnah Colony", 
        "Satellite Town", 
        "Farooqabad", 
        "Model Town", 
        "Khurrianwala", 
        "Railway Colony", 
        "Ghousia Colony", 
        "Hassan Town", 
        "Tandlianwala Road", 
        "Chak No. 240 GB", 
        "Maqbool Road", 
        "Garden Town", 
        "Madina Town", 
        "Chak Jhumra", 
        "Sharif Pura", 
        "Chak 97 GB", 
        "Chak 59 GB", 
        "Saddar Bazar", 
        "Nazimabad", 
        "Anarkali Bazaar", 
        "Ravi Town", 
        "Basti Nizam Din", 
        "Amin Town", 
        "Gulshan-e-Habib", 
        "Muhammad Nagar", 
        "Chak No. 58 GB", 
        "Qasim Town"
      ]},
      { city: "Jatoi Shimali", suburbs: ["Jatoi Town", "Chowk Munda"] },
      { city: "Jauharabad", suburbs: ["Sargodha Road", "Chowk Jauharabad"] },
      { city: "Jhang", suburbs: ["Satellite Town", "Railway Road", "Gojra Road"] },
      { city: "Jhang Sadar", suburbs: ["Gohar Town", "Chak No. 63"] },
      { city: "Jhawarian", suburbs: ["Railway Station Area", "Main Bazar"] },
      { city: "Jhelum", suburbs: [
        "Cantt Area", 
        "Civil Lines", 
        "Satellite Town", 
        "Model Town", 
        "Machine Mohalla", 
        "Muhammadi Chowk", 
        "Bilal Town", 
        "Islamia School Road", 
        "Railway Road", 
        "Sarai Alamgir", 
        "Kala Gujran", 
        "Dhok Jumma", 
        "Bukhsh Colony", 
        "Gul Afshan Colony", 
        "Fatehpur", 
        "Chowk Chabutra", 
        "Goharabad", 
        "Dhoke Firdous", 
        "Naya Mohalla", 
        "Nighat Colony", 
        "Mujahidabad", 
        "Khansama Colony", 
        "Housing Colony", 
        "Shandar Chowk", 
        "River View Colony", 
        "City Housing Society", 
        "Saima Town", 
        "Tahlianwala", 
        "Mangla Road", 
        "Dhoke Abdullah", 
        "Kutchery Road", 
        "Darapur", 
        "Gulshan Town", 
        "Jada", 
        "Al-Bilal Town", 
        "Naseerabad", 
        "Chak Daulat", 
        "Chak Naurang", 
        "Mangla Cantt", 
        "Khewra", 
        "Saroba Village", 
        "Shahpur", 
        "Jinnah Colony", 
        "Bara Dari", 
        "Bagh Mohalla", 
        "Bagh Colony", 
        "Kot Dhamiak", 
        "Jhelum City", 
        "Mohallah Islamia", 
        "Mohallah Eid Gah", 
        "Saddar Bazar", 
        "Kala Pahar", 
        "Gulshan Colony", 
        "Bukhari Colony"
      ]},
      { city: "Kabirwala", suburbs: ["Kabirwala City", "Khanewal Road"] },
      { city: "Kahna Nau", suburbs: ["Model Town", "Nishat Colony"] },
      { city: "Kahuta", suburbs: ["Model Town", "Kahuta Road"] },
      { city: "Kalabagh", suburbs: ["Kalabagh Dam Area", "Lalazar Colony"] },
      { city: "Kalaswala", suburbs: ["Kalaswala Center", "Mianwali Road"] },
      { city: "Kaleke Mandi", suburbs: ["Kaleke Main Bazar"] },
      { city: "Kallar Kahar", suburbs: ["Motorway Area", "Kallar Kahar Town"] },
      { city: "Kalur Kot", suburbs: ["Kalur Kot Town", "Basti Awan"] },
      { city: "Kamalia", suburbs: [
        "Main Bazaar", 
        "Tariqabad", 
        "Farid Town", 
        "Madina Town", 
        "Gulshan-e-Ravi", 
        "Islamia Colony", 
        "Ghaziabad", 
        "Saddar Bazar", 
        "Hassan Colony", 
        "Faisal Colony", 
        "Iqbal Nagar", 
        "Railway Colony", 
        "Baghbanpura", 
        "Mohalla Sadiqabad", 
        "Nishat Colony", 
        "Basti Eidgah", 
        "Bashir Colony", 
        "Rehmanpura", 
        "Saeedabad", 
        "Khan Colony", 
        "Chak 739 G.B.", 
        "Muneerabad", 
        "Ali Town", 
        "Sultan Colony", 
        "Mehar Colony", 
        "Karamat Colony", 
        "Toba Road", 
        "Niazi Colony"
      ]},
      { city: "Kamar Mushani", suburbs: ["Mushani Town", "Chak 157"] },
      { city: "Kamoke", suburbs: ["Kamoke City", "Saddar", "Gulzar Colony"] },
      { city: "Kamra", suburbs: ["Kamra Cantt", "GT Road"] },
      { city: "Kanganpur", suburbs: ["Kanganpur Bazar"] },
      { city: "Karor", suburbs: ["Karor City", "Chowk Azam"] },
      { city: "Kasur", suburbs: ["Kot Radha Kishan", "Mustafabad", "Raiwind"] },
      { city: "Keshupur", suburbs: ["Keshupur Center"] },
      { city: "Khairpur Tamiwali", suburbs: ["Khairpur City"] },
      { city: "Khandowa", suburbs: ["Khandowa Center"] },
      { city: "Khanewal", suburbs: ["Kabirwala", "Tulamba", "Kot Izzat Khan"] },
      { city: "Khanga Dogran", suburbs: ["Chak 83", "Khanga Town"] },
      { city: "Khangarh", suburbs: ["Khangarh Center"] },
      { city: "Khanpur", suburbs: ["Lodhran Road", "Khanpur Center"] },
      { city: "Kharian", suburbs: ["Main Kharian", "Sara-e-Alamgir"] },
      { city: "Khewra", suburbs: ["Salt Mines", "Khewra Town"] },
      { city: "Khurrianwala", suburbs: ["Samundri Road"] },
      { city: "Khushab", suburbs: [
        "Khushab City", 
        "Jauharabad", 
        "Katha Saghral", 
        "Hadali", 
        "Mitha Tiwana", 
        "Noorpur Thal", 
        "Nowshera", 
        "Chak No. 50 DB", 
        "Bandial", 
        "Adhi Kot", 
        "Pail-Piran", 
        "Khaliqabad", 
        "Dera Tang", 
        "Nali Shumali", 
        "Chak 44 MB", 
        "Ali Pur", 
        "Sargodha Road", 
        "Dhokri", 
        "Qaidabad", 
        "Khabakki", 
        "Uchali", 
        "Jaba", 
        "Dhak", 
        "Sakesar", 
        "Warcha", 
        "Soon Valley", 
        "Sandral", 
        "Chitta", 
        "Mardwal", 
        "Padhrar", 
        "Kanhatti", 
        "Anga"
      ]},
      { city: "Kohror Pakka", suburbs: ["Main Road"] },
      { city: "Kot Addu Tehsil", suburbs: ["Kot Addu City"] },
      { city: "Kot Ghulam Muhammad", suburbs: ["Main Bazaar"] },
      { city: "Kot Mumin", suburbs: ["Main Kot Mumin"] },
      { city: "Kot Radha Kishan", suburbs: ["Radha Bazar"] },
      { city: "Kot Rajkour", suburbs: ["Rajkour Bazar"] },
      { city: "Kot Samaba", suburbs: ["Samaba Town"] },
      { city: "Kot Sultan", suburbs: ["Kot Sultan Bazar"] },
      { city: "Kotli Loharan", suburbs: ["Main Bazar"] },
      { city: "Kundian", suburbs: ["Kundian Town"] },
      { city: "Kunjah", suburbs: ["Kunjah Town"] },
      { city: "Ladhewala Waraich", suburbs: ["Waraich Town"] },
      {city: "Lahore",
        suburbs: [
          "Gulberg", 
          "Model Town", 
          "Johar Town", 
          "Cantt", 
          "Shadman", 
          "DHA", 
          "Bahria Town", 
          "Allama Iqbal Town", 
          "Garden Town", 
          "Township", 
          "Samanabad", 
          "Faisal Town", 
          "Sabzazar", 
          "Valencia Town", 
          "Wapda Town", 
          "Green Town", 
          "Barki", 
          "Mughalpura", 
          "Shahdara", 
          "Harbanspura", 
          "Iqbal Town", 
          "Raiwind", 
          "Saddar", 
          "Gulshan-e-Ravi", 
          "Nishtar Town", 
          "Cantt View Society", 
          "Defence Road", 
          "Kalma Chowk", 
          "Bedian Road", 
          "Jubilee Town", 
          "Eden City", 
          "Paragon City", 
          "Al-Hafeez Gardens", 
          "Al Rehman Garden", 
          "LDA Avenue", 
          "NFC Society", 
          "Punjab Society", 
          "Nasheman-e-Iqbal", 
          "Model Colony", 
          "Shalimar", 
          "Badami Bagh", 
          "Ravi Road", 
          "Chungi Amar Sidhu", 
          "Ichhra", 
          "Mayo Gardens", 
          "Islampura", 
          "Kot Lakhpat", 
          "Muslim Town", 
          "Mochi Gate", 
          "Bilal Ganj", 
          "Gari Shahu", 
          "Shah Kamal", 
          "Mohlanwal", 
          "Wahdat Colony", 
          "Garhi Shahu", 
          "China Scheme", 
          "Singhpura", 
          "Shah Alam Market", 
          "Ferozepur Road", 
          "The Mall", 
          "Qila Gujjar Singh", 
          "Rewaz Garden", 
          "Empress Road", 
          "Shah Jamal", 
          "Lakhshmi Chowk", 
          "Samnabad", 
          "Chowk Yateem Khana", 
          "New Muslim Town", 
          "Bhatta Chowk", 
          "Awan Town", 
          "Bagh Gul Begum", 
          "Model Town Link Road", 
          "Sham Nagar", 
          "Main Boulevard", 
          "Gulshan-e-Lahore", 
          "Riwind Road", 
          "Fateh Garh", 
          "Manga Mandi", 
          "Jallo", 
          "Burki", 
          "Kahna Nau", 
          "Kot Abdul Malik", 
          "Maraka", 
          "Thokar Niaz Baig", 
          "Multan Road", 
          "Sunder Industrial Estate", 
          "Walton", 
          "Lakshmi Chowk", 
          "Hall Road", 
          "Anarkali", 
          "Mozang", 
          "Chowk Nakhuda", 
          "Hajveri Town", 
          "Bund Road", 
          "Kot Khawaja Saeed", 
          "Chohan Road", 
          "Iqbal Park", 
          "Hassan Town", 
          "Sunfort Gardens", 
          "Alhamra Town", 
          "Al-Kabir Town", 
          "Gulshan-e-Ahbab", 
          "Marghzar Colony", 
          "Bagh-e-Iram", 
          "Dubai Town", 
          "Nawab Town", 
          "Cavalry Ground", 
          "Askari", 
          "Nishter Colony", 
          "Abid Market", 
          "Sadiq Colony", 
          "Sheikhupura Road", 
          "Lakhu Dehar", 
          "Liberty Market", 
          "Siddiqia Colony", 
          "Tajpura", 
          "Shahdara Town", 
          "Daroghawala", 
          "Azam Gardens", 
          "Peco Road", 
          "Nabi Pura", 
          "Lytton Road", 
          "Allama Iqbal Road", 
          "Gulshan-e-Faraz", 
          "Timber Market", 
          "Data Darbar", 
          "Minar-e-Pakistan", 
          "Dharampura", 
          "Chah Miran", 
          "Bansanwala Bazaar", 
          "Shadbagh", 
          "Bhatti Gate", 
          "Haji Camp", 
          "Railway Station Area", 
          "Shahdara Bagh", 
          "Sabzi Mandi", 
          "Gawalmandi", 
          "Pak Arab Society", 
          "Palm City", 
          "Khuda Buksh Colony", 
          "Divine Gardens", 
          "Sukh Chayn Gardens", 
          "Omega Residencia", 
          "Kings Town", 
          "Westwood Colony", 
          "Nawankot", 
          "Kacha Jail Road", 
          "Mehmood Booti", 
          "Ali Town"
        ]},
      { city: "Lala Musa", suburbs: ["Lala Musa Town"] },
      { city: "Lalian", suburbs: ["Lalian Town"] },
      { city: "Layyah", suburbs: ["Layyah City"] },
      { city: "Layyah District", suburbs: ["District Center"] },
      { city: "Liliani", suburbs: ["Liliani Town"] },
      { city: "Lodhran", suburbs: ["Lodhran City"] },
      { city: "Mailsi", suburbs: ["Mailsi City"] },
      { city: "Malakwal", suburbs: ["Malakwal City"] },
      { city: "Malakwal City", suburbs: ["City Center"] },
      { city: "Mamu Kanjan", suburbs: ["Kanjan Town"] },
      { city: "Mananwala", suburbs: ["Mananwala City"] },
      { city: "Mandi Bahauddin", suburbs: [
        "Main Bazaar", 
        "Saddar Bazar", 
        "Gulshan-e-Hayat", 
        "College Road", 
        "Sufi City", 
        "Gulshan Colony", 
        "Railway Colony", 
        "Farooq-e-Azam Town", 
        "Munshi Mohalla", 
        "Rasul Nagar", 
        "Wasu", 
        "Phalia", 
        "Sargodha Road", 
        "Malikwal", 
        "Chak No. 44", 
        "Chillianwala", 
        "Mohalla Islamia", 
        "Shafqatabad", 
        "Katchery Road", 
        "Quaid-e-Azam Colony", 
        "Nawababad", 
        "Jinnah Colony", 
        "Shaheedanwali", 
        "Mohalla Rasoolpura", 
        "Rasul Town", 
        "Chak Bandi", 
        "Dhoke Kasib", 
        "Umer Town", 
        "Pindi Road", 
        "Kuthiala Sheikhan", 
        "Chak No. 38", 
        "Khutri", 
        "Chak Basawa", 
        "Qadirabad Colony"
      ]},
      { city: "Mandi Bahauddin District", suburbs: ["Bahauddin Center"] },
      { city: "Mangla", suburbs: ["Mangla Dam", "Mangla Town"] },
      { city: "Mankera", suburbs: ["Mankera City"] },
      { city: "Mehmand Chak", suburbs: ["Chak Center"] },
      { city: "Mian Channun", suburbs: ["Channun Town"] },
      { city: "Mianke Mor", suburbs: ["Mianke Mor City"] },
      { city: "Mianwali", suburbs: [
        "Mohalla Mian Sultan", 
        "Civil Lines", 
        "Wapda Colony", 
        "Saddar Bazar", 
        "Namal Town", 
        "Gulberg Town", 
        "Chak No. 10", 
        "Chakrala", 
        "Watta Khel", 
        "Rokhri", 
        "Paikhel", 
        "Allama Iqbal Colony", 
        "Railway Colony", 
        "Gulshan Colony", 
        "Tibba Mahajir", 
        "Ballokhel", 
        "Mochh", 
        "Khattak Colony", 
        "Muazzamabad", 
        "Gharibabad", 
        "Hospital Road", 
        "Tola Bangi Khel", 
        "Muslim Town", 
        "Qureshi Abad", 
        "Niazi Town", 
        "Dher Umid Ali Shah", 
        "Essa Khel", 
        "Kundian", 
        "Chidroo", 
        "Chashma Colony", 
        "Mianwali Cantt", 
        "Kamar Mushani", 
        "Kacha Gujrat", 
        "Kalabagh", 
        "Bhangi Khel", 
        "Chhidru", 
        "Tarakhel", 
        "Lal Pura", 
        "Doaba"
      ]},
      { city: "Minchinabad", suburbs: ["Minchinabad Center"] },
      { city: "Mitha Tiwana", suburbs: ["Mitha City"] },
      { city: "Moza Shahwala", suburbs: ["Moza Center"] },
      { city: "Multan", suburbs: [
        "Shah Rukn-e-Alam", 
        "Gulgasht Colony", 
        "Cantt", 
        "Qasim Bela", 
        "Shershah Town", 
        "Wapda Town", 
        "New Multan", 
        "Model Town", 
        "Bosan Road", 
        "Mumtazabad", 
        "Jalalabad", 
        "Sabzazar Colony", 
        "Green Town", 
        "Tariq Road", 
        "MDA Chowk", 
        "Lodhi Colony", 
        "Al-Mustafa Colony", 
        "Hussain Agahi", 
        "Chungi No. 9", 
        "Chungi No. 6", 
        "Al-Noor Garden", 
        "Vehari Road", 
        "Northern Bypass", 
        "Suraj Miani", 
        "Pul Moj Darya", 
        "Buch Villas", 
        "Garden Town", 
        "Khudadad Colony", 
        "Saddar Bazaar", 
        "Dera Adda", 
        "Peer Khursheed Colony", 
        "Gulshan Market", 
        "Qasimpur Colony", 
        "Fatima Jinnah Town", 
        "Gulshan-e-Yousaf", 
        "Pak Arab Fertilizer Colony", 
        "Industrial Estate", 
        "Khanewal Road", 
        "Makhdoom Rasheed", 
        "Ghanta Ghar", 
        "Wheat Market", 
        "Seetal Mari", 
        "Ahsan Colony", 
        "Hassan Parwana Colony", 
        "Old Shujabad Road", 
        "Daultala", 
        "Pak Gate", 
        "Katchery Road", 
        "Pul Bararan", 
        "Nishtar Road", 
        "Larr Colony", 
        "Bahawalpur Bypass", 
        "Muzaffarabad", 
        "Harbanspura", 
        "Sajid Awan Colony", 
        "Jamilabad", 
        "Madina Town", 
        "Sher Shah Colony", 
        "Bahadurpur", 
        "Moosa Pak Colony", 
        "Z Town", 
        "Airport Road", 
        "Sheikhupura Colony", 
        "Gulistan Colony", 
        "Multan Public School Road", 
        "Gulberg Colony", 
        "Sultan Colony", 
        "Meharban Colony", 
        "Basti Malook", 
        "Chah Boharwala", 
        "Hazoori Bagh Colony", 
        "Punjab Govt Servants Housing Scheme", 
        "Jinnah Town", 
        "Piran Ghaib Road", 
        "Raza Abad", 
        "Ghous Colony", 
        "Defence Housing Authority (DHA) Multan"
      ]},
      { city: "Vehari", suburbs: [
        "People's Colony", 
        "Machiwal", 
        "College Town", 
        "Sikandar Town", 
        "Luddan", 
        "Thingi", 
        "Danewal", 
        "Mitru", 
        "Mailsi Road", 
        "Gagoo Mandi", 
        "Jamalpur", 
        "Model Town", 
        "H Block", 
        "Railway Colony", 
        "Fareed Town", 
        "Anwar Colony", 
        "Vehari Cantt", 
        "Danywal", 
        "Mian Channu Road", 
        "Sharqi Colony", 
        "Naseerabad", 
        "Chak 9 WB", 
        "Mianpur", 
        "Qadirpur Raan", 
        "Khanewal Road", 
        "Burewala", 
        "Karampur", 
        "Chak 187 EB", 
        "Karampur Road", 
        "Hajiabad", 
        "Chak 45 WB", 
        "Gulshan Colony", 
        "Karamat Colony"
      ]},
      { city: "Multan District", suburbs: ["Multan City"] },
      { city: "Muridke", suburbs: ["Muridke City"] },
      { city: "Murree", suburbs: ["Mall Road", "Kashmir Point"] },
      { city: "Mustafabad", suburbs: ["Mustafabad Town"] },
      { city: "Muzaffargarh", suburbs: ["Muzaffargarh City"] },
      { city: "Nankana Sahib", suburbs: ["Nankana City"] },
      { city: "Narang Mandi", suburbs: ["Narang Town"] },
      { city: "Narowal", suburbs: ["Narowal City"] },
      { city: "Naushahra Virkan", suburbs: ["Naushahra Town"] },
      { city: "Nazir Town", suburbs: ["Nazir City"] },
      { city: "Okara", suburbs: ["Cantt", "City Center"] },
      { city: "Pakki Shagwanwali", suburbs: ["Pakki City"] },
      { city: "Pakpattan", suburbs: [
        "Farid Town", 
        "College Town", 
        "Shams Colony", 
        "Model Town", 
        "Sharif Pura", 
        "Chak Bedi", 
        "Old City Pakpattan", 
        "Saddar Bazar", 
        "Al-Farooq Colony", 
        "Rehmat Colony", 
        "Noor Pur", 
        "Civil Lines", 
        "Iqbal Nagar", 
        "Bashir Town", 
        "Green Town", 
        "Gulshan-e-Farid", 
        "Mohalla Peer Ghani", 
        "Housing Colony", 
        "Liaquat Town", 
        "Chak 46 EB", 
        "Chak 45 EB", 
        "Raza Abad", 
        "Wahdat Colony", 
        "Hussain Colony", 
        "Pir Khana Mohalla", 
        "Qaboola Town", 
        "Malka Hans", 
        "Arifwala Road", 
        "Chak Naghan"
      ]},
      { city: "Pasrur", suburbs: ["Pasrur City"] },
      { city: "Pattoki", suburbs: ["Pattoki Town"] },
      { city: "Phalia", suburbs: ["Phalia City"] },
      { city: "Pind Dadan Khan", suburbs: ["Pind City"] },
      { city: "Pindi Bhattian", suburbs: ["Pindi Bhattian City"] },
      { city: "Pindi Gheb", suburbs: ["Pindi Gheb Center"] },
      { city: "Pir Mahal", suburbs: ["Pir Mahal Town"] },
      { city: "Qadirpur Ran", suburbs: ["Qadirpur City"] },
      { city: "Qila Didar Singh", suburbs: ["Qila City"] },
      { city: "Rabwah", suburbs: ["Chenab Nagar"] },
      { city: "Rahim Yar Khan", suburbs: ["Model Town", "Satellite Town", "Cantt"] },
      { city: "Rahimyar Khan District", suburbs: ["District Center"] },
      { city: "Raiwind", suburbs: ["Raiwind City"] },
      { city: "Raja Jang", suburbs: ["Raja Town"] },
      { city: "Rajanpur", suburbs: ["Rajanpur City"] },
      { city: "Rasulnagar", suburbs: ["Rasul City"] },
      { city: "Rawalpindi", suburbs: [
        "Satellite Town", 
        "Saddar", 
        "Bahria Town", 
        "Askari", 
        "DHA Phase 1-4", 
        "Peshawar Road", 
        "Murree Road", 
        "Chaklala Scheme 1-3", 
        "Gulraiz Housing Scheme", 
        "Westridge", 
        "Fazaia Colony", 
        "Tench Bhata", 
        "Commercial Market", 
        "Dhok Chaudhrian", 
        "Dhok Kala Khan", 
        "Dhok Ratta", 
        "Chandni Chowk", 
        "Asghar Mall Scheme", 
        "Khayaban-e-Sir Syed", 
        "New Lalazar", 
        "Afshan Colony", 
        "Ali Town", 
        "Adiala Road", 
        "Chur Chowk", 
        "Pir Wadhai", 
        "People's Colony", 
        "Banni Chowk", 
        "Dhoke Hassu", 
        "Dhoke Mangtal", 
        "Dhoke Kashmirian", 
        "Shamsabad", 
        "Kashmir Colony", 
        "Airport Housing Society", 
        "Media Town", 
        "PWD Housing Society", 
        "Judicial Colony", 
        "Pakistan Town", 
        "Lalazar", 
        "Rawat", 
        "Rawal Town", 
        "Rehmanabad", 
        "Pindi Club", 
        "Gulistan Colony", 
        "Ayub Colony", 
        "Kalma Chowk", 
        "Committee Chowk", 
        "Quaid-e-Azam Colony", 
        "Gulshanabad", 
        "Meharabad", 
        "Sir Syed Colony", 
        "Raja Bazaar", 
        "Kallar Syedan", 
        "Morgah", 
        "Chaklala Cantt", 
        "Mughalabad", 
        "Bakra Mandi", 
        "Sadiqabad", 
        "Katchery Chowk", 
        "Sher Zaman Colony", 
        "Banaras Colony", 
        "Allahabad", 
        "Sangral Town", 
        "Gulshan-e-Iqbal", 
        "Defence View", 
        "Royal Avenue", 
        "Korang Town", 
        "Harley Street", 
        "Dhoke Elahi Baksh", 
        "Qasimabad", 
        "Shah Khalid Colony", 
        "Khayaban-e-Iqbal", 
        "Kahuta Road", 
        "Jhanda Chichi", 
        "Aliabad", 
        "Awan Town", 
        "Baraf Khana Chowk"
      ]},
      { city: "Rawalpindi District", suburbs: ["District Center"] },
      { city: "Renala Khurd", suburbs: ["Renala Town"] },
      { city: "Rojhan", suburbs: ["Rojhan City"] },
      { city: "Sadiqabad", suburbs: ["Model Town"] },
      { city: "Sahiwal", suburbs: ["Cantt", "City Center"] },
      { city: "Sambrial", suburbs: ["Main Sambrial"] },
      { city: "Sangla Hill", suburbs: ["Sangla City"] },
      { city: "Sanjwal", suburbs: ["Cantt", "City Center"] },
      { city: "Sarai Alamgir", suburbs: ["Alamgir City"] },
      { city: "Sarai Sidhu", suburbs: ["Sidhu Town"] },
      { city: "Sargodha", suburbs: [
        "Satellite Town", 
        "Model Town", 
        "Civic Center", 
        "University Town", 
        "Cantt Area", 
        "Gulshan-e-Iqbal", 
        "Khushab Road", 
        "Katchery Bazar", 
        "Block 17", 
        "Block 18", 
        "New Satellite Town", 
        "Farooq Colony", 
        "Miani Town", 
        "Shaheen Colony", 
        "Islamia Colony", 
        "Hajjipura", 
        "Askari Colony", 
        "Liaqat Colony", 
        "Civil Lines", 
        "Khayyam Chowk", 
        "Faisal Colony", 
        "Shamsher Town", 
        "Gulberg Town", 
        "Housing Colony", 
        "Qainchi Mor", 
        "Defence View", 
        "Istaqlalabad Colony", 
        "Royal City", 
        "Pind Makan", 
        "Aziz Bhatti Town", 
        "Jinnah Colony", 
        "Pak Town", 
        "Sajid Town", 
        "Green Town", 
        "Noor Hayat Colony", 
        "Kirana Road", 
        "Factory Area", 
        "Qasim Park", 
        "Sheikh Colony", 
        "University Road", 
        "Siraj Colony", 
        "Chak 47 NB", 
        "Shahpur City", 
        "Kot Fareed", 
        "Jhal Chakian", 
        "Sargodha Bypass", 
        "Khushab Bypass", 
        "Kohinoor Town", 
        "Muzaffar Colony", 
        "Bagh-e-Millat", 
        "Satellite Town Extension", 
        "Malik Colony", 
        "Ashraf Town", 
        "Raza Town", 
        "Bhalwal Road", 
        "Fazal Town", 
        "Faisalabad Road", 
        "Gill Colony", 
        "Jinnah Park", 
        "PAF Road", 
        "Chungi No. 9", 
        "Gulshan-e-Sardar", 
        "Sikandar Town", 
        "PMA Road", 
        "Bilal Town", 
        "Chowk Jhalar"
      ]},
      { city: "Shahkot Tehsil", suburbs: ["Shahkot City"] },
      { city: "Shahpur", suburbs: ["Shahpur Center"] },
      { city: "Shahr Sultan", suburbs: ["Sultan Town"] },
      { city: "Shakargarh", suburbs: ["Shakar Town"] },
      { city: "Sharqpur", suburbs: ["Sharqpur Town"] },
      { city: "Sheikhupura", suburbs: ["City Center", "Cantt"] },
      { city: "Shorkot", suburbs: ["Cantt", "Township"] },
      { city: "Shujaabad", suburbs: ["City Center"] },
      { city: "Sialkot", suburbs: [
        "Model Town", 
        "Citi Housing", 
        "Cantt Area", 
        "Saddar Bazar", 
        "Ugoke", 
        "Sialkot Airport Road", 
        "Kashmir Road", 
        "Shahabpura", 
        "Hunterpura", 
        "Pakka Garha", 
        "Neka Pura", 
        "Paris Road", 
        "Defence Road", 
        "Hajipura", 
        "Gohadpur", 
        "Mujahid Road", 
        "Khawaja Safdar Road", 
        "Saddar Cantt", 
        "Daska Road", 
        "Sambrial", 
        "Haji Pura", 
        "Kharota Syedan", 
        "Small Industrial Estate", 
        "Gulshan Iqbal Park", 
        "Rangpura", 
        "Saeed Colony", 
        "Kashmir Colony", 
        "Mubarak Pura", 
        "Islamia Park", 
        "Bhoth", 
        "Kotli Loharan", 
        "Pasrur Road", 
        "Jinnah Park", 
        "Sialkot Bypass", 
        "Gujranwala Road", 
        "Gulshan Colony", 
        "Sambrial Town", 
        "Defence Housing Scheme", 
        "Aziz Bhatti Shaheed Road", 
        "Sialkot Motorway City", 
        "Lahore Road", 
        "Muradpur", 
        "Abbot Road", 
        "Al Rehman Garden", 
        "Tariq Road", 
        "Roras Road", 
        "Mughalpura", 
        "Qila Kalar Wala", 
        "College Road", 
        "Shafi Da Bhatta", 
        "Allama Iqbal Town", 
        "Behram Key", 
        "Nawaz Sharif Park", 
        "Green Wood Street", 
        "Nizamabad", 
        "Kotli Behram", 
        "Dheera Sandha", 
        "Khiyali Gate", 
        "Jandar Bazar", 
        "Jinnah Colony", 
        "Shuhada Road", 
        "Garrison Housing", 
        "Garden Town", 
        "Factory Area"
      ]},
      { city: "Sillanwali", suburbs: ["Sillanwali City"] },
      { city: "Sodhra", suburbs: ["Sodhra Town"] },
      { city: "Sukheke Mandi", suburbs: ["Sukheke Town"] },
      { city: "Surkhpur", suburbs: ["Surkhpur Town"] },
      { city: "Talagang", suburbs: ["Talagang Center"] },
      { city: "Talamba", suburbs: ["Talamba Town"] },
      { city: "Tandlianwala", suburbs: ["City Center"] },
      { city: "Taunsa", suburbs: ["Taunsa Sharif"] },
      { city: "Toba Tek Singh", suburbs: ["Toba City"] },
      { city: "Umerkot", suburbs: ["City Center"] },
      { city: "Vihari", suburbs: ["City Center"] },
      { city: "Wah", suburbs: ["Wah Cantt"] },
      { city: "Warburton", suburbs: ["Warburton City"] },
      { city: "Wazirabad", suburbs: [
        "Ali Pur Chatta", 
        "Daska Road", 
        "Gujranwala Road", 
        "Railway Road", 
        "Saddar Bazar", 
        "Gondlanwala", 
        "Gondlawala", 
        "Nizamabad", 
        "Sialkot Road", 
        "Bagrian", 
        "Dhounkal", 
        "Nowshera Virkan", 
        "Kot Nainan", 
        "Nizam Pura", 
        "Rattowal", 
        "Kot Saleem", 
        "Aimanabad", 
        "Ghakkar Mandi", 
        "Sheikhupura Road", 
        "Ahmed Nagar Chattha", 
        "Rasool Nagar", 
        "Harrar", 
        "Chak Chattha", 
        "Gujrat Road", 
        "Jinnah Colony", 
        "Sharifpura", 
        "Ladhewala Warraich", 
        "Wazirabad Cantt", 
        "Manzoorabad", 
        "Chowk Saharan", 
        "Qila Didar Singh", 
        "Kassoki Road"
      ]},
      { city: "West Punjab", suburbs: ["Model Colony"] },
      { city: "Yazman", suburbs: ["City Center"] },
      { city: "Zafarwal", suburbs: ["Zafarwal Center"] },
      { city: "Zahir Pir", suburbs: ["City Center"] },

    //   Sindh
    { city: "Adilpur", suburbs: ["Adilpur City Center", "Gul Bagh", "Chak Road"] },
    { city: "Badin", suburbs: ["Model Town", "Golarchi", "Kadhan", "Seerani", "Talhar"] },
    { city: "Bagarji", suburbs: ["Bagarji Town", "Jamal Shah Colony", "Sangi Road"] },
    { city: "Bandhi", suburbs: ["Bandhi City", "Tharushah Road"] },
    { city: "Berani", suburbs: ["Berani Town", "Chak No. 4"] },
    { city: "Bhan", suburbs: ["Bhan Saeedabad", "Rajo Dero"] },
    { city: "Bhiria", suburbs: ["Bhiria Road", "Bhiria City", "Tharo Shakh"] },
    { city: "Bhit Shah", suburbs: ["Bhit Shah Town", "Shrine Area", "Sindh University Colony"] },
    { city: "Bozdar Wada", suburbs: ["Bozdar Main", "Village Wada"] },
    { city: "Bulri", suburbs: ["Bulri Shah Karim", "Bulri Town"] },
    { city: "Chak", suburbs: ["Chak Bazar", "Main Road Chak"] },
    { city: "Chamber", suburbs: ["Chamber Town", "Haji Abdullah Colony"] },
    { city: "Chhor", suburbs: ["Chhor Cantonment", "Bazaar Area"] },
    { city: "Chuhar Jamali", suburbs: ["Chuhar Jamali Center", "Main Road"] },
    { city: "Dadu", suburbs: [
      "New Dadu", 
      "Old Dadu", 
      "Johi", 
      "Mehar", 
      "Khairpur Nathan Shah", 
      "Phulji Station", 
      "Bakho Babar", 
      "Kachho", 
      "Piyaro Goth", 
      "Morgah", 
      "Gharibabad", 
      "Shaheed Makhdoom Bilawal", 
      "Ahmed Khan Chandio", 
      "Pir Shakh", 
      "Village Rahu", 
      "Radhan", 
      "Shah Panjo Sultan", 
      "Kotri", 
      "Sehwan", 
      "Bhan Saeedabad", 
      "Sita Road", 
      "Khudabad", 
      "Daur", 
      "Wahi Pandhi", 
      "Faridabad", 
      "Chhini", 
      "Pir Bux Colony", 
      "Manjhand", 
      "Lakhi Shah Saddar", 
      "Jhangara Bajara", 
      "Pat Sharif", 
      "Darro Mohalla"
    ]},
    { city: "Daromehar", suburbs: ["Daromehar City", "Wahdat Colony"] },
    { city: "Darya Khan Marri", suburbs: ["Darya Marri Center", "Marri Town"] },
    { city: "Daulatpur", suburbs: ["Daulatpur Town", "Village Area"] },
    { city: "Daur", suburbs: ["Daur City Center", "Gulzar Colony"] },
    { city: "Dhoro Naro", suburbs: ["Dhoro Naro Center", "Thar Desert Border"] },
    { city: "Digri", suburbs: ["Digri City", "Chowk Market", "Old Digri"] },
    { city: "Diplo", suburbs: ["Diplo Town", "Rani Kot Road"] },
    { city: "Dokri", suburbs: ["Dokri City", "Mehar Road", "Government Colony"] },
    { city: "Gambat", suburbs: ["Gambat City", "Old Gambat", "New Colony"] },
    { city: "Garhiyasin", suburbs: ["Garhiyasin City", "Larkana Road"] },
    { city: "Gharo", suburbs: ["Gharo Town", "Sakhi Abdul Wahab Colony"] },
    { city: "Ghauspur", suburbs: ["Ghauspur City", "Shahpur Road"] },
    { city: "Ghotki", suburbs: ["Ghotki City", "Railway Road", "New Ghotki"] },
    { city: "Goth Garelo", suburbs: ["Garelo City Center", "Goth Market"] },
    { city: "Goth Phulji", suburbs: ["Phulji Town", "Village Area"] },
    { city: "Goth Radhan", suburbs: ["Radhan Town", "Moori Talpur Area"] },
    { city: "Hala", suburbs: ["Hala Old", "Hala New", "Ceramics Town"] },
    { city: "Hingorja", suburbs: ["Hingorja City", "Old Hingorja"] },
    { city: "Hyderabad", suburbs: [
        "Latifabad", 
        "Qasimabad", 
        "Gulistan-e-Sajjad", 
        "Citizen Colony", 
        "Wadhu Wah", 
        "Hussainabad", 
        "Saddar", 
        "Auto Bahn Road", 
        "Thandi Sarak", 
        "Cantt Area", 
        "Gulshan-e-Hadeed", 
        "Phuleli", 
        "Gari Khata", 
        "Chotki Ghitti", 
        "Sarai Ghat", 
        "Market Tower", 
        "Hyder Chowk", 
        "Jamshoro Road", 
        "Mirpurkhas Road", 
        "Baldia Colony", 
        "Shahi Bazaar", 
        "Makki Shah", 
        "Resham Gali", 
        "New Cloth Market", 
        "Paretabad", 
        "Pathan Colony", 
        "Bakra Mandi", 
        "Site Area", 
        "Hala Naka", 
        "Qasim Chowk", 
        "Sindh University Housing Society", 
        "Al-Mustafa Town", 
        "Pakka Qila", 
        "Tando Jam", 
        "Tando Yusuf", 
        "Tando Wali Muhammad", 
        "Tando Mir Mehmood", 
        "Tando Hyder", 
        "Bhitai Town", 
        "Unit No. 6 Latifabad", 
        "Unit No. 7 Latifabad", 
        "Unit No. 8 Latifabad", 
        "Unit No. 10 Latifabad", 
        "Unit No. 11 Latifabad", 
        "Unit No. 12 Latifabad", 
        "Unit No. 9 Latifabad", 
        "Main Qasimabad", 
        "Nasim Nagar", 
        "Gulshan-e-Waseem", 
        "Shoro Goth", 
        "Alamdar Chowk", 
        "American Quarters", 
        "Bahria Town Hyderabad", 
        "Shamsabad", 
        "Kohsar", 
        "Jamaluddin Afghani Town", 
        "Doctor's Colony", 
        "Sachal Sarmast Colony", 
        "Zulfiqar Housing Society", 
        "Sheedi Goth", 
        "Rani Bagh", 
        "Liaquat Colony", 
        "Naseem Nagar Chowk", 
        "Old Power House Colony", 
        "Al-Mustafa Garden", 
        "Nisar Colony", 
        "Ameenabad", 
        "Mehar Ali Housing Scheme", 
        "Royal City Hyderabad", 
        "Khokhar Mohalla"
      ]},
    { city: "Islamkot", suburbs: ["Islamkot City", "Mithi Road", "Thar Area"] },
    { city: "Jacobabad", suburbs: [
        "Civil Lines", 
        "Shikarpur Road", 
        "Railway Colony", 
        "Deputy Bagh", 
        "Gharibabad", 
        "Thull Road", 
        "Abdullah Colony", 
        "Muhammadpur", 
        "Jaffarabad Colony", 
        "Ali Abad", 
        "Airport Road", 
        "Dodapur", 
        "Memon Mohalla", 
        "Hussainabad", 
        "Bakhshapur", 
        "Saleemabad", 
        "Kandhkot Road", 
        "Quaid-e-Azam Road", 
        "Gulshan-e-Iqbal Colony", 
        "Bagh-e-Millat", 
        "Khosa Mohalla", 
        "Mitho Dar", 
        "Mirpur Buriro", 
        "Haji Shah Muhalla", 
        "Old City", 
        "Dilmurad Mohalla", 
        "Shafi Colony", 
        "City Center", 
        "Pir Bux Colony", 
        "Khanpur Road", 
        "Pathan Colony", 
        "Abdul Sattar Colony", 
        "Naseerabad Colony", 
        "Sakhi Wahab Colony", 
        "Saddar Bazar", 
        "Khosa Colony", 
        "Gulshan-e-Haider", 
        "Lal Mohalla", 
        "Bahria Town Road"
      ]},
    { city: "Jamshoro", suburbs: ["Jamshoro City", "LUMHS Area", "Industrial Zone"] },
    { city: "Jati", suburbs: ["Jati City", "Makli Area"] },
    { city: "Jhol", suburbs: ["Jhol Center", "Market Area"] },
    { city: "Johi", suburbs: ["Johi City", "Mehar Road", "Dadu Road"] },
    { city: "Jām Sāhib", suburbs: ["Jām City", "Main Bazaar"] },
    { city: "Kadhan", suburbs: ["Kadhan City Center", "Main Bazaar"] },
    { city: "Kambar", suburbs: ["Kambar City", "Larkana Road"] },
    { city: "Kandhkot", suburbs: ["Kandhkot City", "Railway Road"] },
    { city: "Kandiari", suburbs: ["Kandiari Town", "Old Kandiari"] },
    { city: "Kandiaro", suburbs: ["Kandiaro City", "Kandiaro Bazar"] },
    { city: "Karachi", suburbs: [
        "Clifton", 
        "DHA (Defence Housing Authority)", 
        "Gulshan-e-Iqbal", 
        "Gulistan-e-Jauhar", 
        "Nazimabad", 
        "North Nazimabad", 
        "PECHS (Pakistan Employees Cooperative Housing Society)", 
        "Korangi", 
        "Malir", 
        "Shah Faisal Colony", 
        "Karachi Cantt", 
        "Saddar", 
        "Landhi", 
        "Liaquatabad", 
        "Garden East", 
        "Garden West", 
        "Orangi Town", 
        "Lyari", 
        "Manzoor Colony", 
        "Akhtar Colony", 
        "Shireen Jinnah Colony", 
        "Federal B Area", 
        "Buffer Zone", 
        "North Karachi", 
        "New Karachi", 
        "Scheme 33", 
        "Bahria Town Karachi", 
        "Surjani Town", 
        "Safoora Goth", 
        "University Road", 
        "KDA Scheme 1", 
        "KDA Scheme 33", 
        "KDA Scheme 5", 
        "Model Colony", 
        "Kharadar", 
        "Mithadar", 
        "Ranchore Line", 
        "Soldier Bazaar", 
        "Jamshed Road", 
        "Mehmoodabad", 
        "Azam Basti", 
        "Defence View", 
        "Saddar Town", 
        "Hasrat Mohani Colony", 
        "Guru Mandir", 
        "Paposh Nagar", 
        "Tariq Road", 
        "Shahrah-e-Faisal", 
        "Hill Park", 
        "Seaview", 
        "Mahmudabad", 
        "Gulshan-e-Maymar", 
        "Saadi Town", 
        "Gulshan-e-Hadeed", 
        "Steel Town", 
        "Korangi Industrial Area", 
        "SITE Area", 
        "Hawksbay", 
        "Keamari", 
        "Fishermen Colony", 
        "Ancholi", 
        "Yaseenabad", 
        "Water Pump", 
        "Johar Mor", 
        "Abul Hassan Isphahani Road", 
        "Gulberg", 
        "New Rizvia Society", 
        "Askari III", 
        "Askari IV", 
        "Garden", 
        "Jinnah Avenue", 
        "Zamzama", 
        "Burns Road", 
        "Bolton Market", 
        "Hub River Road", 
        "Gizri", 
        "Bahadurabad", 
        "Karsaz", 
        "Navy Housing Scheme", 
        "Tipu Sultan Road", 
        "Taiser Town", 
        "Khada Market", 
        "Maripur", 
        "Mujahid Colony", 
        "Abdullah Haroon Road", 
        "PIB Colony", 
        "Allama Iqbal Colony", 
        "Rashid Minhas Road", 
        "Jinnah International Airport Area", 
        "Model Town", 
        "Falaknaz Dreams", 
        "Al-Hilal Society", 
        "Haidery", 
        "Khokhrapar", 
        "Nagan Chowrangi", 
        "Sohrab Goth", 
        "Metroville", 
        "NIPA", 
        "Bilal Colony", 
        "Johar Block", 
        "Garden City", 
        "Mehran Town", 
        "Khuda Ki Basti", 
        "Sindhi Muslim Cooperative Housing Society (SMCHS)", 
        "Karimabad", 
        "Pechs Block 6", 
        "Mahmoodabad No. 3", 
        "Mohammad Ali Society", 
        "Azizabad", 
        "Gulshan-e-Iqbal Block 13-D", 
        "Federal B Area Block 7", 
        "Defence Phase VIII", 
        "Defence Phase VI", 
        "Defence Phase V", 
        "Karsaz Road", 
        "Sher Shah Colony", 
        "Saeedabad", 
        "Jamia Millia", 
        "Shah Latif Town", 
        "Lalukhet", 
        "Landhi Town", 
        "New Town", 
        "Naval Colony", 
        "PNS Mehran", 
        "Rafi Bungalows", 
        "Bin Qasim Town"
      ]},
    { city: "Karaundi", suburbs: ["Karaundi Town"] },
    { city: "Kario Ghanwar", suburbs: ["Kario Center"] },
    { city: "Kashmor", suburbs: ["Kashmor City", "Old Kashmor"] },
    { city: "Keti Bandar", suburbs: ["Keti Bandar Port", "Fisherman's Colony"] },
    { city: "Khadro", suburbs: ["Khadro Town", "Market Area"] },
    { city: "Khairpur", suburbs: [
      "Khairpur City", 
      "Pir Jo Goth", 
      "Kot Diji", 
      "Gambat", 
      "Setharja", 
      "Sobho Dero", 
      "Ranipur", 
      "Luari Sharif", 
      "Thari Mirwah", 
      "Faiz Ganj", 
      "Pacca Chang", 
      "Ahmedpur", 
      "Babarloi", 
      "Hingorja", 
      "Mirwah Canal", 
      "Nizamani Mohalla", 
      "Ali Murad Mohalla", 
      "Bhutta Mohalla", 
      "Ghulam Murtaza Colony", 
      "Shaikh Mohalla", 
      "Kot Banglow", 
      "Firdous Colony", 
      "Choundiko", 
      "Nawab Khan Jatoi Colony", 
      "Kouro Khan Colony", 
      "Shadi Shaheed", 
      "Chak", 
      "Agra Taj Colony", 
      "Pir Illahi Bux Colony", 
      "Shah Abdul Latif Colony", 
      "Rasoolabad", 
      "Haji Sawan Colony", 
      "Shahi Bazar", 
      "Luari Mohalla", 
      "Old Sukkur Road", 
      "Jamra"
    ]},
    { city: "Khairpur Mir’s", suburbs: ["Mir’s City Center", "Gulshan Colony"] },
    { city: "Khairpur Nathan Shah", suburbs: ["Nathan Shah Town", "Village Area"] },
    { city: "Khanpur Mahar", suburbs: ["Khanpur Town", "Mahar Colony"] },
    { city: "Kot Diji", suburbs: ["Kot Diji Fort", "Diji Colony"] },
    { city: "Kotri", suburbs: ["Kotri City", "Industrial Area"] },
    { city: "Kunri", suburbs: ["Kunri City", "Red Chilli Market"] },
    { city: "Lakhi", suburbs: ["Lakhi Town", "Village Road"] },
    { city: "Larkana", suburbs: [
        "Shaikh Zayed Colony", 
        "Ali Goharabad", 
        "Hyderi Mohalla", 
        "Baghdadi Mohalla", 
        "Rehmatpur", 
        "Dhamraha Colony", 
        "Haji Nawab Colony", 
        "Murad Wahan", 
        "Sachal Colony", 
        "Waleed Town", 
        "Pir Sher Road", 
        "Gareebabad", 
        "Empire Road", 
        "Bakrani Road", 
        "Bunguldero Road", 
        "Anaj Mandi", 
        "Gulshan-e-Saeed", 
        "Ali Abad", 
        "Dargah Yar Mohammad Kalhoro", 
        "Miro Khan Road", 
        "Karani Colony", 
        "Naseerabad Colony", 
        "Jinnah Bagh", 
        "Housing Society", 
        "Gulbahar Colony", 
        "Khichi Mohalla", 
        "Hussaini Mohalla", 
        "Abid Colony", 
        "Resham Gali", 
        "Shikarpur Road", 
        "Civil Lines", 
        "Bunder Road", 
        "Qafila Serai", 
        "Allahabad", 
        "Pakho Road", 
        "Railway Colony", 
        "Awan Colony", 
        "Dodai", 
        "Pir Bux Colony", 
        "Muhammad Pura", 
        "Kausar Mill Area", 
        "Shaikh Mohalla", 
        "Pathan Colony", 
        "Madina Colony", 
        "Memon Mohalla", 
        "Wagan Road", 
        "Faridabad", 
        "Kennedy Market", 
        "Nawab Colony", 
        "Khuda Bakhsh Colony", 
        "Hathoonabad", 
        "Lal Shaban Colony", 
        "Government Officers Colony"
      ]},
    { city: "Madeji", suburbs: ["Madeji City", "Main Market"] },
    { city: "Malir Cantonment", suburbs: ["Malir Cantt", "Korangi Area"] },
    { city: "Matiari", suburbs: ["Matiari City", "Main Matiari Market"] },
    { city: "Matli", suburbs: ["Matli City", "Golarchi Road"] },
    { city: "Mehar", suburbs: ["Mehar City", "Old Mehar"] },
    { city: "Miro Khan", suburbs: ["Miro Khan Center", "Village Area"] },
    { city: "Mirpur Bhtoro", suburbs: ["Bhtoro Town", "Railway Road"] },
    { city: "Mirpur Khas", suburbs: ["Mirpur City", "Cantt Area", "Market Area"] },
    { city: "Mirpur Mathelo", suburbs: ["Mathelo Town", "Gulzar Colony"] },
    { city: "Mirpur Sakro", suburbs: ["Mirpur Sakro City", "Keti Bandar Road"] },
    { city: "Mirwah Gorchani", suburbs: ["Gorchani Town"] },
    { city: "Mithi", suburbs: ["Mithi City", "Desert Area"] },
    { city: "Moro", suburbs: ["Moro City", "Station Road"] },
    { city: "Nabisar", suburbs: ["Nabisar City", "Thar Desert"] },
    { city: "Nasirabad", suburbs: ["Nasirabad City", "Bazar Area"] },
    { city: "Naudero", suburbs: ["Naudero Town", "Larkana Road"] },
    { city: "Naukot", suburbs: ["Naukot Fort", "Main Naukot"] },
    { city: "Naushahro Firoz", suburbs: ["Naushahro City", "Firoz Market"] },
    { city: "Nawabshah", suburbs: [
        "Sakrand Road", 
        "Society Chowk", 
        "Qazi Ahmed Road", 
        "Mujahid Colony", 
        "Gulshan-e-Hadeed", 
        "Qazi Town", 
        "Civil Lines", 
        "Saddar Bazar", 
        "Old Nawabshah City", 
        "Airport Road", 
        "Mohini Bazaar", 
        "Housing Society", 
        "Latif Colony", 
        "Mehran Colony", 
        "Chandni Chowk", 
        "Habib Colony", 
        "Nawab Colony", 
        "Chandni Chowk", 
        "Sir Syed Town", 
        "Munawar Colony", 
        "Gulshan-e-Shahbaz", 
        "Gulshan-e-Iqbal", 
        "Majeed Colony", 
        "New Saeedabad", 
        "Doctors Colony", 
        "Haji Naseerabad", 
        "Qazi Ahmed Town", 
        "Bucheri Road", 
        "Lal Bakhsh Colony", 
        "Gharibabad", 
        "Bandhi", 
        "Masjid Road", 
        "Ali Town", 
        "Shahbaz Colony", 
        "Riaz Colony", 
        "Mehrabpur Road", 
        "Resham Gali", 
        "Nawabshah Bypass", 
        "Shaheed Benazirabad", 
        "Benazir Town", 
        "Jinnah Road", 
        "Marium Road", 
        "Bukhari Town", 
        "Defence Colony", 
        "Industrial Area", 
        "Professor's Colony", 
        "Abbas Town"
      ]},
    { city: "New Bādāh", suburbs: ["Badah Center", "Market Area"] },
    { city: "Pad Idan", suburbs: ["Pad Idan City", "Railway Colony"] },
    { city: "Pano Aqil", suburbs: ["Pano Aqil Town", "Cantt Area"] },
    { city: "Pir Jo Goth", suburbs: ["Pir Jo Goth City"] },
    { city: "Pithoro", suburbs: ["Pithoro Town"] },
    { city: "Rajo Khanani", suburbs: ["Khanani Town", "Market"] },
    { city: "Ranipur", suburbs: ["Ranipur City", "Sufi Shrine Area"] },
    { city: "Ratodero", suburbs: ["Ratodero City"] },
    { city: "Rohri", suburbs: ["Rohri City", "Railway Station", "Old Town"] },
    { city: "Rustam", suburbs: ["Rustam City"] },
    { city: "Sakrand", suburbs: ["Sakrand City", "National Highway"] },
    { city: "Samaro", suburbs: ["Samaro City", "Village Area"] },
    { city: "Sanghar", suburbs: ["Sanghar City", "Thar Road"] },
    { city: "Sann", suburbs: ["Sann City", "Market Area"] },
    { city: "Sehwan", suburbs: ["Sehwan Sharif", "Shrine Area"] },
    { city: "Setharja Old", suburbs: ["Setharja Town"] },
    { city: "Shahdad Kot", suburbs: ["Shahdad Kot City", "Old Kot"] },
    { city: "Shahdadpur", suburbs: ["Shahdadpur City", "Tando Adam Road"] },
    { city: "Shahpur Chakar", suburbs: ["Shahpur City", "Chakar Colony"] },
    { city: "Shikarpur", suburbs: [
        "Stuart Ganj", 
        "Jagan Nath Bazaar", 
        "Civil Lines", 
        "Hathi Dar", 
        "Nim Khabar", 
        "Lakhi Gate", 
        "New Shikarpur", 
        "Gulshan-e-Iqbal", 
        "Jahan Khan Road", 
        "Rustam Road", 
        "Madeji", 
        "Wagon Colony", 
        "Garhi Yasin", 
        "Abdullah Colony", 
        "Haji Ghabi", 
        "Hussainabad", 
        "Chak", 
        "Sultankot", 
        "Gharhi Dakho", 
        "Muhammadi Mohalla", 
        "Shahbaz Colony", 
        "Khanpur", 
        "Babu Muhalla", 
        "Lal Muhalla", 
        "Wazirabad", 
        "Bhirkan", 
        "Baghban Muhalla", 
        "Gulshan-e-Faiz", 
        "Zarkhail Muhalla", 
        "Lodhran Road", 
        "Dargah Road", 
        "Saddar Bazar", 
        "Old Shikarpur City", 
        "Mughal Colony", 
        "Abdul Rehman Colony", 
        "Shahi Bazaar", 
        "Qazi Mohalla", 
        "Islamabad Colony", 
        "Jagan Mohalla", 
        "Bismillah Colony"
      ]},
    { city: "Sinjhoro", suburbs: ["Sinjhoro Town", "Village Area"] },
    { city: "Sobhodero", suburbs: ["Sobhodero Town"] },
    { city: "Sukkur", suburbs: [
        "Military Road", 
        "Shikarpur Road", 
        "New Pind", 
        "Qureshi Goth", 
        "Wazirabad", 
        "Airport Road", 
        "Numaish Colony", 
        "Minara Road", 
        "Barrage Colony", 
        "Sadat Colony", 
        "Nishtar Road", 
        "Shalimar", 
        "Abdullah Town", 
        "Gulshan-e-Iqbal", 
        "Lab-e-Mehran", 
        "Qureshi Road", 
        "Muhammad Bin Qasim Town", 
        "Adam Shah Colony", 
        "Haji Ghulam Rasool Colony", 
        "Darya Khan Shaikh", 
        "New Sukkur", 
        "Jinnah Chowk", 
        "Old Sukkur", 
        "Bunder Road", 
        "Bagarji", 
        "Clock Tower", 
        "Workshop Road", 
        "Mission Road", 
        "City Point", 
        "Hussaini Road", 
        "Jehangirabad", 
        "Bachal Shah Miani", 
        "Saddar Bazar", 
        "Gharibabad", 
        "Anwarabad", 
        "Sukkur Township", 
        "Salehpat", 
        "Ali Wahan", 
        "Patni", 
        "Pano Aqil", 
        "Kandhra", 
        "Site Area", 
        "Khawaja Goth", 
        "Government Employees Cooperative Housing Society (GECHS)", 
        "Nawa Goth", 
        "Rohri", 
        "Ali Bux Khoso Goth", 
        "Kausar Mill Area", 
        "Nawab Muhalla", 
        "Memon Society", 
        "PIA Employees Housing Society", 
        "Sukkur Cooperative Housing Society", 
        "Lloyd Barrage Colony", 
        "Raza Goth", 
        "Railway Colony", 
        "Mehmoodabad", 
        "Ghousia Colony", 
        "Islam Colony"
      ]},
    { city: "Sīta Road", suburbs: ["Sita Road Town", "Village Road"] },
    { city: "Talhar", suburbs: ["Talhar City"] },
    { city: "Tando Adam", suburbs: [
      "Main Bazaar", 
      "Khuda Ki Basti", 
      "Madina Colony", 
      "Latifabad", 
      "Gharibabad", 
      "New Hyderabad Road", 
      "Allahabad Colony", 
      "Khan Colony", 
      "Railway Colony", 
      "Shah Latif Colony", 
      "Pir Muhammad Colony", 
      "Salar Goth", 
      "Aliabad", 
      "Bhittai Town", 
      "Pathan Colony", 
      "Laghari Mohalla", 
      "Saeedabad", 
      "Bux Ali Goth", 
      "Pir Buksh Colony", 
      "Qureshi Mohalla", 
      "Chakiwara", 
      "Khanqah Mohalla", 
      "Taj Colony", 
      "Mir Wah Road", 
      "Makrani Mohalla", 
      "Jhanda Chowk", 
      "Shamsabad", 
      "Nawaz Colony"
    ]},
    { city: "Tando Allahyar", suburbs: ["Tando Allahyar City", "Market Area"] },
    { city: "Tando Bago", suburbs: ["Tando Bago City", "Main Road"] },
    { city: "Tando Jam", suburbs: ["Tando Jam City", "Agricultural University"] },
    { city: "Tando Mitha Khan", suburbs: ["Mitha Khan Center"] },
    { city: "Tando Muhammad Khan", suburbs: ["Muhammad Khan City"] },
    { city: "Tangwani", suburbs: ["Tangwani City"] },
    { city: "Tharu Shah", suburbs: ["Tharu City"] },
    { city: "Thatta", suburbs: ["Thatta City", "Makli", "Buhara"] },
    { city: "Thul", suburbs: ["Thul City", "Thul Center"] },
    { city: "Ubauro", suburbs: ["Ubauro Town", "Railway Colony"] },
    { city: "Umarkot", suburbs: ["Umarkot City", "Fort Area"] },
    { city: "Umerkot District", suburbs: ["Umerkot City Center"] },
    { city: "Warah", suburbs: ["Warah Town"] },
    // Islamabad Capital Territory
    {
      city: "Islamabad",
      suburbs: [
        "F-6", "F-7", "F-8", "F-10", "F-11", "F-15", "G-5", "G-6", "G-7", "G-8", "G-9",
        "G-10", "G-11", "G-13", "G-14", "I-8", "I-9", "I-10", "I-11", "H-8", "H-9",
        "E-7", "E-11", "Blue Area", "Diplomatic Enclave", "Bahria Town", "DHA Phase 1",
        "DHA Phase 2", "DHA Phase 3", "DHA Phase 5", "PWD", "Soan Garden", "Chak Shahzad",
        "Banigala", "Bhara Kahu", "Margalla Town", "Shah Allah Ditta", "Golra", "Pir Sohawa",
        "Bani Gala", "Korang Town", "Media Town", "Gulberg Greens", "B-17", "C-15", "C-16",
        "FECHS", "Faisal Town", "Jinnah Garden", "Fazaia Housing Scheme", "PWD", "Naval Anchorage",
        "Top City", "Airport Housing Society", "Park View City", "Top City 1", "Alipur Farash",
        "Khanpur Dam", "National Police Foundation", "Multi Gardens", "PECHS", "Ghauri Town",
        "Doctors Town", "PWD Housing Scheme", "Jinnah Town"
      ]
    }
  ];

export const getSuburbs=(city)=> {
    const cityData = suburbs.find(item => item.city.toLowerCase() === city.toLowerCase());
    return cityData ? cityData.suburbs : [];
}