
export const metadata = {
    title: "Aussie Motors | Listing",
    description: "Generated by create next app",
  };
  
  export default function RootLayout({ children }) {
    return <>{children}</>;
  }
  