import { ComparisonProvider } from "@/contexts/comparison";

export const metadata = {
    title: "Auto Wheels | Find New Cars",
    description: "Generated by create next app",
  };
  
  export default function RootLayout({ children }) {
    return <ComparisonProvider>{children}</ComparisonProvider>;
  }
  